#!/usr/bin/perl
use strict;
print "<pre lang=\"sql\">";
my $buffer = undef;
while (<>){
    s/\s*\z/\n/;
    print $buffer if defined $buffer;
    $buffer = $_;
}
$buffer =~ s/\s*$//;
print "$buffer</pre>";
